Repository eclipse-edc/DataDashboard, pull requests merged in 2023-09, with the labels that each got.

#68 fix: use actual apiKey instead of dummy value
  src/modules/app/app.module.ts
Labels: bug

#69 refactor: remove unused library
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#72 build(deps): bump edc-connector-client to 0.2.0-beta3
  package-lock.json
  package.json
  src/modules/app/app.module.ts
  src/modules/mgmt-api-client/api/asset.service.ts
Labels: dependencies

#81 feat: switch `ContractDefinition` to connector client
  README.md
  package-lock.json
  package.json
  src/modules/edc-demo/components/contract-definition-editor-dialog/contract-definition-editor-dialog.component.html
  src/modules/edc-demo/components/contract-definition-editor-dialog/contract-definition-editor-dialog.component.ts
  src/modules/edc-demo/components/contract-definition-viewer/contract-definition-viewer.component.html
  src/modules/edc-demo/components/contract-definition-viewer/contract-definition-viewer.component.ts
  src/modules/mgmt-api-client/api/asset.service.ts
  src/modules/mgmt-api-client/api/contractDefinition.service.ts
  src/modules/mgmt-api-client/model/edc-connector-entities.ts
  src/modules/mgmt-api-client/model/index.ts
Labels: enhancement

#88 fix: add apikey to the client
  src/modules/app/app.module.ts
Labels: bug

#90 feat: connector client: switch PolicyService
  package.json
  src/modules/edc-demo/components/contract-definition-editor-dialog/contract-definition-editor-dialog.component.ts
  src/modules/edc-demo/components/new-policy-dialog/new-policy-dialog.component.html
  src/modules/edc-demo/components/new-policy-dialog/new-policy-dialog.component.ts
  src/modules/edc-demo/components/policy-view/policy-view.component.html
  src/modules/edc-demo/components/policy-view/policy-view.component.ts
  src/modules/mgmt-api-client/api/policy.service.ts
  src/modules/mgmt-api-client/model/edc-connector-entities.ts
Labels: enhancement

#99 fix: Set Correct Value for operandLeft in assetSelector in ContractDefinition
  src/modules/edc-demo/components/contract-definition-editor-dialog/contract-definition-editor-dialog.component.ts
Labels: bug
