Repository eclipse-edc/DataDashboard, pull requests merged in 2023-08, with the labels that each got.

#31 build: configure dependabot
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/dependabot.yml
  .github/workflows/pull-request.yaml
  .github/workflows/scan-pull-request.yaml
Labels: enhancement, dependencies

#29 docs: add DR for connector client
  docs/developer/decision-records/2023-08-09-connector-client/README.md
  docs/developer/decision-records/README.md
Labels: documentation

#42 fix: update show message method to get custom error messages
  src/modules/edc-demo/components/asset-viewer/asset-viewer.component.ts
  src/modules/edc-demo/components/policy-view/policy-view.component.ts
Labels: enhancement

#46 fix: use ID in deletion dialog to prevent undefined displayed
  src/modules/edc-demo/components/asset-viewer/asset-viewer.component.ts
Labels: enhancement

#52 feat: use connector client in `AssetService`
  .gitignore
  README.md
  deployment/conf/consumer-connector.config/addresses.json
  deployment/conf/consumer-connector.config/configuration.properties
  deployment/conf/consumer-connector.config/vault-keys.p12
  deployment/conf/consumer-connector.config/vault.properties
  deployment/conf/provider-connector.config/addresses.json
  deployment/conf/provider-connector.config/configuration.properties
  deployment/conf/provider-connector.config/vault-keys.p12
  deployment/conf/provider-connector.config/vault.properties
  deployment/connector/Dockerfile
  deployment/connector/build.gradle.kts
  deployment/connector/gradle/libs.versions.toml
  deployment/connector/gradle/wrapper/gradle-wrapper.jar
  deployment/connector/gradle/wrapper/gradle-wrapper.properties
  deployment/connector/gradlew
  deployment/connector/gradlew.bat
  deployment/nginx.compose.conf
  docker-compose.yml
  package-lock.json
  package.json
  proxy.conf.json
  src/assets/config/app.config.json
  src/modules/app/app-config.service.ts
  src/modules/app/app.module.ts
  src/modules/edc-demo/components/asset-editor-dialog/asset-editor-dialog.component.ts
  src/modules/edc-demo/components/asset-viewer/asset-viewer.component.ts
  src/modules/edc-demo/components/introduction/introduction.component.html
  src/modules/mgmt-api-client/api/asset.service.ts
  src/modules/mgmt-api-client/model/asset.ts
  src/modules/mgmt-api-client/model/assetEntryDto.ts
  src/modules/mgmt-api-client/model/assetRequestDto.ts
  src/modules/mgmt-api-client/model/assetResponseDto.ts
  src/modules/mgmt-api-client/model/contractOffer.ts
  src/modules/mgmt-api-client/model/edc-connector-entities.ts
  src/modules/mgmt-api-client/model/index.ts
  src/modules/mgmt-api-client/model/models.ts
Labels: enhancement
